# Generated by Django 5.2.1 on 2025-06-03 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('job_id', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinLengthValidator(0.0), django.core.validators.MaxLengthValidator(10)])),
                ('commission_pct', models.CharField(max_length=15)),
                ('manager_id', models.CharField(max_length=15)),
                ('department_id', models.CharField(max_length=15)),
            ],
        ),
    ]
