# Generated by Django 5.2.1 on 2025-06-04 06:23

from django.db import migrations

def add_default_roles(apps, schema_editor):
    Role = apps.get_model("myapp", "Role")
    default_roles = [
        {"name": "Admin", "description": "Full Access"},
        {"name": "Editor", "description": "Can edti content"},
        {"name": "Viewer", "description": "Read-only access"},
    ]

    for role in default_roles:
        Role.objects.update_or_create(
            name = role["name"],
            defaults = {
                "description": role["description"]
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_roles)
    ]
