# Generated by Django 5.2.1 on 2025-06-04 06:28

from django.db import migrations

def populate_full_name(apps, schema_editor):
    UserProfile = apps.get_model("myapp", "UserProfile")
    for profile in UserProfile.objects.all():
        profile.full_name = f"{profile.first_name} {profile.last_name}"
        profile.save()
       

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile'),
    ]

    operations = [
        migrations.RunPython(populate_full_name)
    ]
